### ISSUE TITLE
Warning and no image generation 

### ISSUE THREAD

**Issue by jomiquel** [jawira/mysql-draw#11]
The proccess fails with one of my databases when I try to generate midi or maxi size images. It works right with the same database but mini size. I attach the output I get.

Great work, I love it.

mysql-draw version: v0.1.2
PHP version: 7.4.30
OS: MacOS Monterey 12.6

[maxi.log](https://github.com/jawira/mysql-draw/files/9718360/maxi.log)
[midi.log](https://github.com/jawira/mysql-draw/files/9718361/midi.log)

**Comment by axio-vincent** [comment]
Hello, I confirm I got the same problem for those options, though the result for `mini` is great already.

Note that the `mini|midi|maxi` seems to work only in puml format !

**Comment by jawira** [comment]
I will check the problem this month, please be patient.

**Comment by axio-vincent** [comment]
> @jomiquel @axio-vincent can you please provide the diagrams in puml format please ?

It's a private project... I can't this sorry

**Comment by jawira** [comment]
Hello, I found the problem. 

Internally, `mysql-draw` only generates `.puml` files, that's why I rely on _PlantUml public server_ to do the conversion `.puml`→`.png` (<http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000>). 

But in order to prevent abuse, _PlantUml public server_ does not allow to convert big images-like your diagram. That's why you have an error, and that's why "mini" format still works.

There's is no easy solution here, what I suggest is to only use `mysql-draw` to generate `.puml` files, and then install PlantUml locally to make the conversion by yourself.

What do you think?

**Comment by axio-vincent** [comment]
> **EDIT:** I successfully generated a png diagram from your log files, I had to crate my own PlantUml server (https://hub.docker.com/r/plantuml/plantuml-server) and also configure PLANTUML_LIMIT_SIZE=10000 since your diagram is rally big, the result is a ~900K image. I can add an option to specify a custom PlantUml server like `mysql-draw --planutml=http://127.0.0.1:8080 --url=....`. What do you think about this? I see no point of implementing this if nobody is going to use it.

Ok I understand that the plant uml online prevent from generating big images so I have to download it and execute it localy.

I think a note about this should be added to the doc ? :)

**Comment by jawira** [comment]
You have to follow two steps:

1. Generate `puml` file
2. Convert `puml` to `png` in your pc

**Step 1**

first you have to create your diagram in `puml` format (use `--format`) because this format doesn't use PlantUml server.

```console
// generate database.puml
$ mysql-draw --url=mysql://user:pass@host/db_name --format=puml
```

**Step 2**

Now use plantuml (you can [download the jar file](https://plantuml.com/en/download)) in your computer to convert your diagram to `png`, additionally you have to set `PLANTUML_LIMIT_SIZE` because your diagram is big ([more info in FAQ](https://plantuml.com/en/faq)):

```console
// Convert diagram to png
$ PLANTUML_LIMIT_SIZE=10000 java -jar ./plantuml.jar -tpng database.puml
```

And that's it, you have your png image.

**Aditional info**

Depending how you installed `plantuml` you might have an executable, just be sure you are using a recent version (latest PlantUml version is Version 1.2022.8).

```console
$ PLANTUML_LIMIT_SIZE=10000 plantuml -tpng diagram.puml
```

Finally, if you want you can use  [jawira/plantuml](https://github.com/jawira/plantuml) to download PlantUml.

**Comment by jawira** [comment]
Hello, I have updated `mysql-draw`. Now it will use PlantUML if you have installed it.

Now you can specify the location of `plantuml.jar` (https://plantuml.com/en/download). Then use `--jar` option, this should fix your problems.

https://github.com/jawira/mysql-draw/releases/download/v0.2.0/mysql-draw.phar
